openapi: 3.0.0
info:
  title: Uyuni API
  description: Welcome to the Uyuni API. By using the included API calls, you can more easily automate many of the tasks you perform everyday. All API calls are grouped by common functionality.
  version: 0.1.9

servers:
  - url: http://localhost:8080/uyuni
    description: Uyuni API

paths:
  /system/listSystems:
    get:
      parameters:
        - name: systemKey
          in: query
          type: string
          description: System session ID
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
  /system/getDetails:
    get:
      parameters:
        - name: systemKey
          in: query
          type: string
          description: System session ID
        - name: serverId
          in: query
          type: integer
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array

